### ISSUE TITLE
Does it work with remote repositories?

### ISSUE THREAD

**Issue by clucstart** [jgehring/pepper#10]
Does it work with remote repositories?

**Comment by jgehring** [comment]
It works with remote Subversion repositories, but git or hg repositories have to be local.

**Comment by clucstart** [comment]
Thank you. Do you have instructions how to connect to remote SVN repositories?

**Comment by clucstart** [comment]
Hi Jonas. Thanks for the reply. This could be a great tool - it's just I don't have any clue how to run it against a remote SVN repository. Help please!

**Comment by clucstart** [comment]
I am looking for a way to run on a remote SVN repository that requires username and password.

**Comment by clucstart** [comment]
Maybe due to the way pepper sends requests, I am getting HTTP 429 "Too many requests" from GitHub.

**Comment by jgehring** [comment]
Usernames and passwords can be set via command-line options. There's also an option for specifying the number of concurrent requests (`--threads`), and I think by default 10 threads are used. If a host complains about too many requests, try specifying a lower number to `--threads`, e.g. 2 or 4.

**Comment by clucstart** [comment]
Thanks. I found the params:
        Options::print("--username=ARG", "Specify a username ARG");
    Options::print("--password=ARG", "Specify a password ARG");
    Options::print("--no-auth-cache", "Do not cache authentication tokens");
    Options::print("--non-interactive", "Do no interactive prompting");
    Options::print("--trunk=ARG", "Trunk is at subdirectory ARG");
    Options::print("--branches=ARG", "Branches are in subdirectory ARG");
    Options::print("--tags=ARG", "Tags are in subdirectory ARG");
    Options::print("--threads=ARG", "Use ARG threads for requesting diffstats");
