### ISSUE TITLE
APR 1.5 is required

### ISSUE THREAD

**Issue by andreasstieger** [jgehring/pepper#6]
version 0.3.3 introduced (https://github.com/jgehring/pepper/compare/0.3.2...0.3.3) use of the following apr functions:

* `apr_hash_this_key`
* `apr_hash_this_key_len`

These are new in apr 1.5, significantly higher than the apr requirement for the lowest version of svn supported by pepper.

The configure should check for apr 1.5 when building with Subversion support.

**Comment by jgehring** [comment]
Sorry for the long delay. Replacing those two calls simplified the code, actually :)
